[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi[standard]>=0.115.12",
    "uvicorn>=0.35.0",
    "firebase-admin>=7.0.0",
    "python-dotenv>=1.0.0"
]
